name: amal_tracker
description: Monthly Amal Tracker - Islamic Practice Tracker App
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Navigation
  go_router: ^14.2.0

  # Network
  dio: ^5.4.3+1
  retrofit: ^4.1.0

  # Local Storage
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.0.0

  # UI
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  lottie: ^3.1.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  fl_chart: ^0.68.0
  percent_indicator: ^4.2.3
  calendar_date_picker2: ^1.1.0
  intl: ^0.20.2
  badges: ^3.1.2
  geolocator: ^12.0.0
  geocoding: ^3.0.0

  # Icons & Assets
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  iconsax: ^0.0.8

  # Utilities
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_localization: ^0.4.0
  connectivity_plus: ^6.1.1
  internet_connection_checker_plus: ^2.5.0

  flutter_local_notifications: ^17.2.4
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  timezone: ^0.9.4
  flutter_timezone: ^5.0.2
  provider: ^6.1.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
  retrofit_generator: ^8.1.0
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/sabeq_logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#04301A"
  image: assets/images/sabeq_logo.png

  android: true
  ios: true

  android_12:
    image: assets/images/sabeq_splash.png
    color: "#04301A"
    icon_background_color: "#04301A"
    branding: assets/images/deenly_branding.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Kalpurush
      fonts:
        - asset: assets/fonts/Kalpurush.ttf
