// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5V1dH6z_9YyDNYO4A2tAOljLbZLEY-Z4',
    appId: '1:399822720867:web:835e9af82d018f2a9e0d56',
    messagingSenderId: '399822720867',
    projectId: 'amal-tracker-by-deenly',
    authDomain: 'amal-tracker-by-deenly.firebaseapp.com',
    storageBucket: 'amal-tracker-by-deenly.firebasestorage.app',
    measurementId: 'G-HL1ZXEB96Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSvp2Igys2RH9h63HkbpVLYy7Z18830lo',
    appId: '1:399822720867:android:851a9e81d13d2ca19e0d56',
    messagingSenderId: '399822720867',
    projectId: 'amal-tracker-by-deenly',
    storageBucket: 'amal-tracker-by-deenly.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLgzyD_UMPPczvvgfK8oGWqx_E6_shcpI',
    appId: '1:399822720867:ios:ce590539f06edf979e0d56',
    messagingSenderId: '399822720867',
    projectId: 'amal-tracker-by-deenly',
    storageBucket: 'amal-tracker-by-deenly.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLgzyD_UMPPczvvgfK8oGWqx_E6_shcpI',
    appId: '1:399822720867:ios:ce590539f06edf979e0d56',
    messagingSenderId: '399822720867',
    projectId: 'amal-tracker-by-deenly',
    storageBucket: 'amal-tracker-by-deenly.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5V1dH6z_9YyDNYO4A2tAOljLbZLEY-Z4',
    appId: '1:399822720867:web:c3d337967d7efb759e0d56',
    messagingSenderId: '399822720867',
    projectId: 'amal-tracker-by-deenly',
    authDomain: 'amal-tracker-by-deenly.firebaseapp.com',
    storageBucket: 'amal-tracker-by-deenly.firebasestorage.app',
    measurementId: 'G-SKRBQ7184K',
  );
}