import 'package:flutter/material.dart';
import 'app_colors.dart';

// ─────────────────────────────────────────────────────────────────────────────
// AppColorTokens — Flutter's standard ThemeExtension mechanism for custom,
// app-specific colors that go beyond ColorScheme (docs.flutter.dev > ThemeExtension).
//
// `AppColorTokens.light` mirrors AmolColors exactly — SAME hex values, so the
// current (light) UI does not change even one pixel.
//
// `AppColorTokens.dark` is a FIRST-DRAFT, auto-generated dark palette (HSL
// lightness/saturation inversion per token role — background/text/border/accent).
// It is meant as a working starting point, not a final design decision — please
// eyeball it on real screens and adjust anything that looks off before shipping.
// ─────────────────────────────────────────────────────────────────────────────
class AppColorTokens extends ThemeExtension<AppColorTokens> {
  const AppColorTokens({
    required this.ambalText,
    required this.amber,
    required this.amber2,
    required this.amber3,
    required this.amberBorder,
    required this.amberDark,
    required this.amberLight,
    required this.amberLight2,
    required this.avatar1,
    required this.avatar2,
    required this.avatar3,
    required this.avatar4,
    required this.avatar5,
    required this.bg,
    required this.blue,
    required this.blue2,
    required this.blueBorder,
    required this.blueLight,
    required this.border,
    required this.border2,
    required this.border3,
    required this.borderLight,
    required this.borderMid,
    required this.borderMid2,
    required this.card,
    required this.cardBg,
    required this.chipBg,
    required this.darkGreen,
    required this.darkGreen2,
    required this.districtBg,
    required this.districtText,
    required this.divider,
    required this.gold,
    required this.gold2,
    required this.goldBg,
    required this.goldBorder,
    required this.goldBorder2,
    required this.goldLight,
    required this.goldLight2,
    required this.goldPale,
    required this.goldText,
    required this.green,
    required this.greenAccent,
    required this.greenBorder,
    required this.greenLight,
    required this.greenMid,
    required this.indigo,
    required this.indigoLight,
    required this.inputBg,
    required this.maafBg,
    required this.maafText,
    required this.midGreen,
    required this.orange,
    required this.orangeLight,
    required this.pageBg,
    required this.pink,
    required this.pink2,
    required this.pinkLight,
    required this.purple,
    required this.purpleBorder,
    required this.purpleLight,
    required this.purplePale,
    required this.rankBronze,
    required this.rankGold,
    required this.rankSilver,
    required this.red,
    required this.red2,
    required this.red3,
    required this.redLight,
    required this.redLight2,
    required this.rose,
    required this.roseLight,
    required this.serialBg,
    required this.serialText,
    required this.skelBase,
    required this.skelBaseDark,
    required this.shimmerHighlight,
    required this.success,
    required this.surfaceAlt,
    required this.tafsirBg,
    required this.teal,
    required this.tealLight,
    required this.textBody,
    required this.textHint,
    required this.textHint2,
    required this.textHint3,
    required this.textMuted,
    required this.textPri,
    required this.textPrimary,
    required this.textSec,
    required this.textSec2,
    required this.textSec3,
    required this.textSec4,
    required this.textSecondary,
  });

  final Color ambalText;
  final Color amber;
  final Color amber2;
  final Color amber3;
  final Color amberBorder;
  final Color amberDark;
  final Color amberLight;
  final Color amberLight2;
  final Color avatar1;
  final Color avatar2;
  final Color avatar3;
  final Color avatar4;
  final Color avatar5;
  final Color bg;
  final Color blue;
  final Color blue2;
  final Color blueBorder;
  final Color blueLight;
  final Color border;
  final Color border2;
  final Color border3;
  final Color borderLight;
  final Color borderMid;
  final Color borderMid2;
  final Color card;
  final Color cardBg;
  final Color chipBg;
  final Color darkGreen;
  final Color darkGreen2;
  final Color districtBg;
  final Color districtText;
  final Color divider;
  final Color gold;
  final Color gold2;
  final Color goldBg;
  final Color goldBorder;
  final Color goldBorder2;
  final Color goldLight;
  final Color goldLight2;
  final Color goldPale;
  final Color goldText;
  final Color green;
  final Color greenAccent;
  final Color greenBorder;
  final Color greenLight;
  final Color greenMid;
  final Color indigo;
  final Color indigoLight;
  final Color inputBg;
  final Color maafBg;
  final Color maafText;
  final Color midGreen;
  final Color orange;
  final Color orangeLight;
  final Color pageBg;
  final Color pink;
  final Color pink2;
  final Color pinkLight;
  final Color purple;
  final Color purpleBorder;
  final Color purpleLight;
  final Color purplePale;
  final Color rankBronze;
  final Color rankGold;
  final Color rankSilver;
  final Color red;
  final Color red2;
  final Color red3;
  final Color redLight;
  final Color redLight2;
  final Color rose;
  final Color roseLight;
  final Color serialBg;
  final Color serialText;
  final Color skelBase;
  final Color skelBaseDark;
  final Color shimmerHighlight;
  final Color success;
  final Color surfaceAlt;
  final Color tafsirBg;
  final Color teal;
  final Color tealLight;
  final Color textBody;
  final Color textHint;
  final Color textHint2;
  final Color textHint3;
  final Color textMuted;
  final Color textPri;
  final Color textPrimary;
  final Color textSec;
  final Color textSec2;
  final Color textSec3;
  final Color textSec4;
  final Color textSecondary;

  static const light = AppColorTokens(
    ambalText: AmolColors.ambalText,
    amber: AmolColors.amber,
    amber2: AmolColors.amber2,
    amber3: AmolColors.amber3,
    amberBorder: AmolColors.amberBorder,
    amberDark: AmolColors.amberDark,
    amberLight: AmolColors.amberLight,
    amberLight2: AmolColors.amberLight2,
    avatar1: AmolColors.avatar1,
    avatar2: AmolColors.avatar2,
    avatar3: AmolColors.avatar3,
    avatar4: AmolColors.avatar4,
    avatar5: AmolColors.avatar5,
    bg: AmolColors.bg,
    blue: AmolColors.blue,
    blue2: AmolColors.blue2,
    blueBorder: AmolColors.blueBorder,
    blueLight: AmolColors.blueLight,
    border: AmolColors.border,
    border2: AmolColors.border2,
    border3: AmolColors.border3,
    borderLight: AmolColors.borderLight,
    borderMid: AmolColors.borderMid,
    borderMid2: AmolColors.borderMid2,
    card: AmolColors.card,
    cardBg: AmolColors.cardBg,
    chipBg: AmolColors.chipBg,
    darkGreen: AmolColors.darkGreen,
    darkGreen2: AmolColors.darkGreen2,
    districtBg: AmolColors.districtBg,
    districtText: AmolColors.districtText,
    divider: AmolColors.divider,
    gold: AmolColors.gold,
    gold2: AmolColors.gold2,
    goldBg: AmolColors.goldBg,
    goldBorder: AmolColors.goldBorder,
    goldBorder2: AmolColors.goldBorder2,
    goldLight: AmolColors.goldLight,
    goldLight2: AmolColors.goldLight2,
    goldPale: AmolColors.goldPale,
    goldText: AmolColors.goldText,
    green: AmolColors.green,
    greenAccent: AmolColors.greenAccent,
    greenBorder: AmolColors.greenBorder,
    greenLight: AmolColors.greenLight,
    greenMid: AmolColors.greenMid,
    indigo: AmolColors.indigo,
    indigoLight: AmolColors.indigoLight,
    inputBg: AmolColors.inputBg,
    maafBg: AmolColors.maafBg,
    maafText: AmolColors.maafText,
    midGreen: AmolColors.midGreen,
    orange: AmolColors.orange,
    orangeLight: AmolColors.orangeLight,
    pageBg: AmolColors.pageBg,
    pink: AmolColors.pink,
    pink2: AmolColors.pink2,
    pinkLight: AmolColors.pinkLight,
    purple: AmolColors.purple,
    purpleBorder: AmolColors.purpleBorder,
    purpleLight: AmolColors.purpleLight,
    purplePale: AmolColors.purplePale,
    rankBronze: AmolColors.rankBronze,
    rankGold: AmolColors.rankGold,
    rankSilver: AmolColors.rankSilver,
    red: AmolColors.red,
    red2: AmolColors.red2,
    red3: AmolColors.red3,
    redLight: AmolColors.redLight,
    redLight2: AmolColors.redLight2,
    rose: AmolColors.rose,
    roseLight: AmolColors.roseLight,
    serialBg: AmolColors.serialBg,
    serialText: AmolColors.serialText,
    skelBase: AmolColors.skelBase,
    skelBaseDark: AmolColors.skelBaseDark,
    shimmerHighlight: AmolColors.shimmerHighlight,
    success: AmolColors.success,
    surfaceAlt: AmolColors.surfaceAlt,
    tafsirBg: AmolColors.tafsirBg,
    teal: AmolColors.teal,
    tealLight: AmolColors.tealLight,
    textBody: AmolColors.textBody,
    textHint: AmolColors.textHint,
    textHint2: AmolColors.textHint2,
    textHint3: AmolColors.textHint3,
    textMuted: AmolColors.textMuted,
    textPri: AmolColors.textPri,
    textPrimary: AmolColors.textPrimary,
    textSec: AmolColors.textSec,
    textSec2: AmolColors.textSec2,
    textSec3: AmolColors.textSec3,
    textSec4: AmolColors.textSec4,
    textSecondary: AmolColors.textSecondary,
  );

  static const dark = AppColorTokens(
    ambalText: Color(0xFFF1E3DA),
    amber: Color(0xFFE8AA41),
    amber2: Color(0xFFF38F6A),
    amber3: Color(0xFFE78B21),
    amberBorder: Color(0xFF4E4522),
    amberDark: Color(0xFFF1E3DA),
    amberLight: Color(0xFF4D3919),
    amberLight2: Color(0xFF4C421A),
    avatar1: Color(0xFF1B5935),
    avatar2: Color(0xFF4A5567),
    avatar3: Color(0xFF986AE6),
    avatar4: Color(0xFF19A7C9),
    avatar5: Color(0xFFB42961),
    bg: Color(0xFF11140F),
    blue: Color(0xFF19A7C9),
    blue2: Color(0xFF137FBA),
    blueBorder: Color(0xFF233F4D),
    blueLight: Color(0xFF1B384B),
    border: Color(0xFF33402F),
    border2: Color(0xFF33402F),
    border3: Color(0xFF33402F),
    borderLight: Color(0xFF2A331F),
    borderMid: Color(0xFF3A4834),
    borderMid2: Color(0xFF3A4834),
    card: Color(0xFF1B211A),
    cardBg: Color(0xFF1B211A),
    chipBg: Color(0xFF1C221A),
    darkGreen: Color(0xFF1B5935),
    darkGreen2: Color(0xFF0B502D),
    districtBg: Color(0xFF181B18),
    districtText: Color(0xFFE1EAE4),
    divider: Color(0xFF262E24),
    gold: Color(0xFFD3B46D),
    gold2: Color(0xFFECCE73),
    goldBg: Color(0xFF201C13),
    goldBorder: Color(0xFF494228),
    goldBorder2: Color(0xFF4F3D22),
    goldLight: Color(0xFF4D3E19),
    goldLight2: Color(0xFF4D3919),
    goldPale: Color(0xFF221E11),
    goldText: Color(0xFFF0EADB),
    green: Color(0xFF28BA5E),
    greenAccent: Color(0xFF6DB68E),
    greenBorder: Color(0xFF313F34),
    greenLight: Color(0xFF293D32),
    greenMid: Color(0xFF40A066),
    indigo: Color(0xFF7A73E0),
    indigoLight: Color(0xFF19254D),
    inputBg: Color(0xFF161A14),
    maafBg: Color(0xFF293D32),
    maafText: Color(0xFF2B8959),
    midGreen: Color(0xFF2B8959),
    orange: Color(0xFFE5743A),
    orangeLight: Color(0xFF4D2619),
    pageBg: Color(0xFF11140F),
    pink: Color(0xFFE677AE),
    pink2: Color(0xFFD6558E),
    pinkLight: Color(0xFF471F36),
    purple: Color(0xFF986AE6),
    purpleBorder: Color(0xFF2A234D),
    purpleLight: Color(0xFF251C4A),
    purplePale: Color(0xFF24194D),
    rankBronze: Color(0xFFCB945D),
    rankGold: Color(0xFFD3B46D),
    rankSilver: Color(0xFFABB6C4),
    red: Color(0xFFE87474),
    red2: Color(0xFFD65555),
    red3: Color(0xFFDF6764),
    redLight: Color(0xFF491D1D),
    redLight2: Color(0xFF4B1B1B),
    rose: Color(0xFFDA4D6C),
    roseLight: Color(0xFF4D191D),
    serialBg: Color(0xFF181B18),
    serialText: Color(0xFFF1F3F1),
    skelBase: Color(0xFF191B18),
    skelBaseDark: Color(0xFF181B18),
    shimmerHighlight: Color(0xFF191A19),
    success: Color(0xFF28BA5E),
    surfaceAlt: Color(0xFF181B18),
    tafsirBg: Color(0xFF171C18),
    teal: Color(0xFF1DADA0),
    tealLight: Color(0xFF1D4940),
    textBody: Color(0xFFE3E8E4),
    textHint: Color(0xFFF2F3F2),
    textHint2: Color(0xFFB0BCBF),
    textHint3: Color(0xFFB2BDB4),
    textMuted: Color(0xFFE4E7E5),
    textPri: Color(0xFFDFECE3),
    textPrimary: Color(0xFFDFECE3),
    textSec: Color(0xFFE4E7E5),
    textSec2: Color(0xFFE4E7E5),
    textSec3: Color(0xFFE4E7E5),
    textSec4: Color(0xFFE3E8E5),
    textSecondary: Color(0xFFE4E7E5),
  );

  @override
  AppColorTokens copyWith({
    Color? ambalText,
    Color? amber,
    Color? amber2,
    Color? amber3,
    Color? amberBorder,
    Color? amberDark,
    Color? amberLight,
    Color? amberLight2,
    Color? avatar1,
    Color? avatar2,
    Color? avatar3,
    Color? avatar4,
    Color? avatar5,
    Color? bg,
    Color? blue,
    Color? blue2,
    Color? blueBorder,
    Color? blueLight,
    Color? border,
    Color? border2,
    Color? border3,
    Color? borderLight,
    Color? borderMid,
    Color? borderMid2,
    Color? card,
    Color? cardBg,
    Color? chipBg,
    Color? darkGreen,
    Color? darkGreen2,
    Color? districtBg,
    Color? districtText,
    Color? divider,
    Color? gold,
    Color? gold2,
    Color? goldBg,
    Color? goldBorder,
    Color? goldBorder2,
    Color? goldLight,
    Color? goldLight2,
    Color? goldPale,
    Color? goldText,
    Color? green,
    Color? greenAccent,
    Color? greenBorder,
    Color? greenLight,
    Color? greenMid,
    Color? indigo,
    Color? indigoLight,
    Color? inputBg,
    Color? maafBg,
    Color? maafText,
    Color? midGreen,
    Color? orange,
    Color? orangeLight,
    Color? pageBg,
    Color? pink,
    Color? pink2,
    Color? pinkLight,
    Color? purple,
    Color? purpleBorder,
    Color? purpleLight,
    Color? purplePale,
    Color? rankBronze,
    Color? rankGold,
    Color? rankSilver,
    Color? red,
    Color? red2,
    Color? red3,
    Color? redLight,
    Color? redLight2,
    Color? rose,
    Color? roseLight,
    Color? serialBg,
    Color? serialText,
    Color? skelBase,
    Color? skelBaseDark,
    Color? shimmerHighlight,
    Color? success,
    Color? surfaceAlt,
    Color? tafsirBg,
    Color? teal,
    Color? tealLight,
    Color? textBody,
    Color? textHint,
    Color? textHint2,
    Color? textHint3,
    Color? textMuted,
    Color? textPri,
    Color? textPrimary,
    Color? textSec,
    Color? textSec2,
    Color? textSec3,
    Color? textSec4,
    Color? textSecondary,
  }) {
    return AppColorTokens(
      ambalText: ambalText ?? this.ambalText,
      amber: amber ?? this.amber,
      amber2: amber2 ?? this.amber2,
      amber3: amber3 ?? this.amber3,
      amberBorder: amberBorder ?? this.amberBorder,
      amberDark: amberDark ?? this.amberDark,
      amberLight: amberLight ?? this.amberLight,
      amberLight2: amberLight2 ?? this.amberLight2,
      avatar1: avatar1 ?? this.avatar1,
      avatar2: avatar2 ?? this.avatar2,
      avatar3: avatar3 ?? this.avatar3,
      avatar4: avatar4 ?? this.avatar4,
      avatar5: avatar5 ?? this.avatar5,
      bg: bg ?? this.bg,
      blue: blue ?? this.blue,
      blue2: blue2 ?? this.blue2,
      blueBorder: blueBorder ?? this.blueBorder,
      blueLight: blueLight ?? this.blueLight,
      border: border ?? this.border,
      border2: border2 ?? this.border2,
      border3: border3 ?? this.border3,
      borderLight: borderLight ?? this.borderLight,
      borderMid: borderMid ?? this.borderMid,
      borderMid2: borderMid2 ?? this.borderMid2,
      card: card ?? this.card,
      cardBg: cardBg ?? this.cardBg,
      chipBg: chipBg ?? this.chipBg,
      darkGreen: darkGreen ?? this.darkGreen,
      darkGreen2: darkGreen2 ?? this.darkGreen2,
      districtBg: districtBg ?? this.districtBg,
      districtText: districtText ?? this.districtText,
      divider: divider ?? this.divider,
      gold: gold ?? this.gold,
      gold2: gold2 ?? this.gold2,
      goldBg: goldBg ?? this.goldBg,
      goldBorder: goldBorder ?? this.goldBorder,
      goldBorder2: goldBorder2 ?? this.goldBorder2,
      goldLight: goldLight ?? this.goldLight,
      goldLight2: goldLight2 ?? this.goldLight2,
      goldPale: goldPale ?? this.goldPale,
      goldText: goldText ?? this.goldText,
      green: green ?? this.green,
      greenAccent: greenAccent ?? this.greenAccent,
      greenBorder: greenBorder ?? this.greenBorder,
      greenLight: greenLight ?? this.greenLight,
      greenMid: greenMid ?? this.greenMid,
      indigo: indigo ?? this.indigo,
      indigoLight: indigoLight ?? this.indigoLight,
      inputBg: inputBg ?? this.inputBg,
      maafBg: maafBg ?? this.maafBg,
      maafText: maafText ?? this.maafText,
      midGreen: midGreen ?? this.midGreen,
      orange: orange ?? this.orange,
      orangeLight: orangeLight ?? this.orangeLight,
      pageBg: pageBg ?? this.pageBg,
      pink: pink ?? this.pink,
      pink2: pink2 ?? this.pink2,
      pinkLight: pinkLight ?? this.pinkLight,
      purple: purple ?? this.purple,
      purpleBorder: purpleBorder ?? this.purpleBorder,
      purpleLight: purpleLight ?? this.purpleLight,
      purplePale: purplePale ?? this.purplePale,
      rankBronze: rankBronze ?? this.rankBronze,
      rankGold: rankGold ?? this.rankGold,
      rankSilver: rankSilver ?? this.rankSilver,
      red: red ?? this.red,
      red2: red2 ?? this.red2,
      red3: red3 ?? this.red3,
      redLight: redLight ?? this.redLight,
      redLight2: redLight2 ?? this.redLight2,
      rose: rose ?? this.rose,
      roseLight: roseLight ?? this.roseLight,
      serialBg: serialBg ?? this.serialBg,
      serialText: serialText ?? this.serialText,
      skelBase: skelBase ?? this.skelBase,
      skelBaseDark: skelBaseDark ?? this.skelBaseDark,
      shimmerHighlight: shimmerHighlight ?? this.shimmerHighlight,
      success: success ?? this.success,
      surfaceAlt: surfaceAlt ?? this.surfaceAlt,
      tafsirBg: tafsirBg ?? this.tafsirBg,
      teal: teal ?? this.teal,
      tealLight: tealLight ?? this.tealLight,
      textBody: textBody ?? this.textBody,
      textHint: textHint ?? this.textHint,
      textHint2: textHint2 ?? this.textHint2,
      textHint3: textHint3 ?? this.textHint3,
      textMuted: textMuted ?? this.textMuted,
      textPri: textPri ?? this.textPri,
      textPrimary: textPrimary ?? this.textPrimary,
      textSec: textSec ?? this.textSec,
      textSec2: textSec2 ?? this.textSec2,
      textSec3: textSec3 ?? this.textSec3,
      textSec4: textSec4 ?? this.textSec4,
      textSecondary: textSecondary ?? this.textSecondary,
    );
  }

  @override
  AppColorTokens lerp(ThemeExtension<AppColorTokens>? other, double t) {
    if (other is! AppColorTokens) return this;
    return AppColorTokens(
      ambalText: Color.lerp(ambalText, other.ambalText, t)!,
      amber: Color.lerp(amber, other.amber, t)!,
      amber2: Color.lerp(amber2, other.amber2, t)!,
      amber3: Color.lerp(amber3, other.amber3, t)!,
      amberBorder: Color.lerp(amberBorder, other.amberBorder, t)!,
      amberDark: Color.lerp(amberDark, other.amberDark, t)!,
      amberLight: Color.lerp(amberLight, other.amberLight, t)!,
      amberLight2: Color.lerp(amberLight2, other.amberLight2, t)!,
      avatar1: Color.lerp(avatar1, other.avatar1, t)!,
      avatar2: Color.lerp(avatar2, other.avatar2, t)!,
      avatar3: Color.lerp(avatar3, other.avatar3, t)!,
      avatar4: Color.lerp(avatar4, other.avatar4, t)!,
      avatar5: Color.lerp(avatar5, other.avatar5, t)!,
      bg: Color.lerp(bg, other.bg, t)!,
      blue: Color.lerp(blue, other.blue, t)!,
      blue2: Color.lerp(blue2, other.blue2, t)!,
      blueBorder: Color.lerp(blueBorder, other.blueBorder, t)!,
      blueLight: Color.lerp(blueLight, other.blueLight, t)!,
      border: Color.lerp(border, other.border, t)!,
      border2: Color.lerp(border2, other.border2, t)!,
      border3: Color.lerp(border3, other.border3, t)!,
      borderLight: Color.lerp(borderLight, other.borderLight, t)!,
      borderMid: Color.lerp(borderMid, other.borderMid, t)!,
      borderMid2: Color.lerp(borderMid2, other.borderMid2, t)!,
      card: Color.lerp(card, other.card, t)!,
      cardBg: Color.lerp(cardBg, other.cardBg, t)!,
      chipBg: Color.lerp(chipBg, other.chipBg, t)!,
      darkGreen: Color.lerp(darkGreen, other.darkGreen, t)!,
      darkGreen2: Color.lerp(darkGreen2, other.darkGreen2, t)!,
      districtBg: Color.lerp(districtBg, other.districtBg, t)!,
      districtText: Color.lerp(districtText, other.districtText, t)!,
      divider: Color.lerp(divider, other.divider, t)!,
      gold: Color.lerp(gold, other.gold, t)!,
      gold2: Color.lerp(gold2, other.gold2, t)!,
      goldBg: Color.lerp(goldBg, other.goldBg, t)!,
      goldBorder: Color.lerp(goldBorder, other.goldBorder, t)!,
      goldBorder2: Color.lerp(goldBorder2, other.goldBorder2, t)!,
      goldLight: Color.lerp(goldLight, other.goldLight, t)!,
      goldLight2: Color.lerp(goldLight2, other.goldLight2, t)!,
      goldPale: Color.lerp(goldPale, other.goldPale, t)!,
      goldText: Color.lerp(goldText, other.goldText, t)!,
      green: Color.lerp(green, other.green, t)!,
      greenAccent: Color.lerp(greenAccent, other.greenAccent, t)!,
      greenBorder: Color.lerp(greenBorder, other.greenBorder, t)!,
      greenLight: Color.lerp(greenLight, other.greenLight, t)!,
      greenMid: Color.lerp(greenMid, other.greenMid, t)!,
      indigo: Color.lerp(indigo, other.indigo, t)!,
      indigoLight: Color.lerp(indigoLight, other.indigoLight, t)!,
      inputBg: Color.lerp(inputBg, other.inputBg, t)!,
      maafBg: Color.lerp(maafBg, other.maafBg, t)!,
      maafText: Color.lerp(maafText, other.maafText, t)!,
      midGreen: Color.lerp(midGreen, other.midGreen, t)!,
      orange: Color.lerp(orange, other.orange, t)!,
      orangeLight: Color.lerp(orangeLight, other.orangeLight, t)!,
      pageBg: Color.lerp(pageBg, other.pageBg, t)!,
      pink: Color.lerp(pink, other.pink, t)!,
      pink2: Color.lerp(pink2, other.pink2, t)!,
      pinkLight: Color.lerp(pinkLight, other.pinkLight, t)!,
      purple: Color.lerp(purple, other.purple, t)!,
      purpleBorder: Color.lerp(purpleBorder, other.purpleBorder, t)!,
      purpleLight: Color.lerp(purpleLight, other.purpleLight, t)!,
      purplePale: Color.lerp(purplePale, other.purplePale, t)!,
      rankBronze: Color.lerp(rankBronze, other.rankBronze, t)!,
      rankGold: Color.lerp(rankGold, other.rankGold, t)!,
      rankSilver: Color.lerp(rankSilver, other.rankSilver, t)!,
      red: Color.lerp(red, other.red, t)!,
      red2: Color.lerp(red2, other.red2, t)!,
      red3: Color.lerp(red3, other.red3, t)!,
      redLight: Color.lerp(redLight, other.redLight, t)!,
      redLight2: Color.lerp(redLight2, other.redLight2, t)!,
      rose: Color.lerp(rose, other.rose, t)!,
      roseLight: Color.lerp(roseLight, other.roseLight, t)!,
      serialBg: Color.lerp(serialBg, other.serialBg, t)!,
      serialText: Color.lerp(serialText, other.serialText, t)!,
      skelBase: Color.lerp(skelBase, other.skelBase, t)!,
      skelBaseDark: Color.lerp(skelBaseDark, other.skelBaseDark, t)!,
      shimmerHighlight: Color.lerp(shimmerHighlight, other.shimmerHighlight, t)!,
      success: Color.lerp(success, other.success, t)!,
      surfaceAlt: Color.lerp(surfaceAlt, other.surfaceAlt, t)!,
      tafsirBg: Color.lerp(tafsirBg, other.tafsirBg, t)!,
      teal: Color.lerp(teal, other.teal, t)!,
      tealLight: Color.lerp(tealLight, other.tealLight, t)!,
      textBody: Color.lerp(textBody, other.textBody, t)!,
      textHint: Color.lerp(textHint, other.textHint, t)!,
      textHint2: Color.lerp(textHint2, other.textHint2, t)!,
      textHint3: Color.lerp(textHint3, other.textHint3, t)!,
      textMuted: Color.lerp(textMuted, other.textMuted, t)!,
      textPri: Color.lerp(textPri, other.textPri, t)!,
      textPrimary: Color.lerp(textPrimary, other.textPrimary, t)!,
      textSec: Color.lerp(textSec, other.textSec, t)!,
      textSec2: Color.lerp(textSec2, other.textSec2, t)!,
      textSec3: Color.lerp(textSec3, other.textSec3, t)!,
      textSec4: Color.lerp(textSec4, other.textSec4, t)!,
      textSecondary: Color.lerp(textSecondary, other.textSecondary, t)!,
    );
  }
}

extension AppColorTokensX on BuildContext {
  AppColorTokens get colors =>
      Theme.of(this).extension<AppColorTokens>() ?? AppColorTokens.light;
}
